GET http://localhost:8079/whatsapp/request/reset

###

POST http://localhost:8079/whatsapp/request/register
Content-Type: application/json

{
  "username": "user1",
  "password": "geheim"
}

###

POST http://localhost:8079/whatsapp/request/register
Content-Type: application/json

{
  "username": "user2",
  "password": "geheim"
}


###

POST http://localhost:8079/whatsapp/request/login
Content-Type: application/json

{
  "username": "user1",
  "password": "geheim"
}


###

GET http://localhost:8079/whatsapp/request/info
Authorization: Bearer eyJraWQiOiJwcml2YXRlS2V5LnBlbSIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJ1cG4iOiJ1c2VyMSIsImlzcyI6Imh0dHBzOi8vYXQuaHRsIiwiZ3JvdXBzIjpbInVzZXIiXSwiaWF0IjoxNjE3NzgxMTAzLCJhdXRoX3RpbWUiOjE2MTc3ODExMDMsImV4cCI6MTYxNzc4MTQ2MywianRpIjoiYjU1YTQwZTQtOGRhYi00MjNhLTkwYzUtOWZkZjIyNzkyYmM2In0.b5Djdz0iM0InW5txUlnoif_nhr__bPrJcbPcs2_TRFf-wbdmlkzRJLCF_gSygYKOKFDO-FE214tyBVA-0cN8mmrR4qjrYcgP-PFHFBDq7pJIwpqDqXAjB2FyvZH1LD7eqOqo5iNtf6lTx05dKpb8xdjWDY4nURAEn0svis4ZVjD8CuB8lPE0Im5iQvoQ1uxbQ-YVIx2div0eo1u8kXGY04DqZ_xcVdNLCWPkcilJ1vgrPOa3Q6ooRATUu42miAtMRWpR-6IxLO6iKhebEp-0ibdxPHj-7LlVttoV3FQQ83aH6eqLVBdVhxOawvM1YqO1G9DGQ3qNfsZmwe_tTImoYw

###


GET http://localhost:8079/whatsapp/request/getAllUsers

###

GET http://localhost:8079/whatsapp/request/getAllGroups

###

GET http://localhost:8079/whatsapp/request/init

###

GET http://localhost:8079/whatsapp/request/getAllMemberships/test


###
